### ---------------------------------------------------------------------------
### FIND SITE INFO
### ---------------------------------------------------------------------------
- name: "Run cleanup function on site_name variable"
  set_fact:
    snow_cleanup_site_name: "{{ site_name | snow_cleanup_site_name }}"
  run_once: True

- name: "Site data from Netbox"
  uri:
    url: "{{ netbox.base_url }}/dcim/sites/?slug={{ cleaned_site_name }}"
    method: GET
    return_content: yes
    status_code: "200"
    headers:
      Content-Type: "application/json"
      Authorization: "Token {{ netbox.api_token }}"
    force_basic_auth: yes
    validate_certs: false
  register: site_data

- name: "setting site_data variable"
  set_fact:
    site_data: "{{ site_data.json.results }}"

# - debug:
#     msg: "{{ site_data }}"

- name: "cleaning up device data into dictionary values"
  set_fact:
    site_data: "{{ site_data | cleanup_site_data }}"
