configuration:
  protocols:
    ospf:
      area:
        - name: "0.0.0.0"
          interface:
            - name: "xe-0/0/5.0"
            - name: "xe-0/0/6.0"
            - name: "lo0.0"
              passive: null
