configuration:
  snmp:
    community:
      authorization: read-only
      clients:
        - name: 10.255.127.0/24
        - name: 0.0.0.0/0
          restrict: null
      name: $home_snmp$
    interface: em0.0
    trap_group:
      - name: SNMP_TRAP
        categories:
          chassis: null
          routing: null
        targets:
          name: 10.255.127.31
        version: v2
      - name: space
        targets:
          name: 10.255.127.33
        version: v2
    trap_options:
      source_address:
        address: "{{ ansible_host }}"
