configuration:
  snmp:
    community:
      authorization: read-only
      clients:
        - name: 10.6.6.0/24
        - name: 0.0.0.0/0
          restrict: null
      name: $home_snmp$
    interface: em0.0
    trap_group:
      - name: space
        targets:
          name: 10.6.6.120
        version: v2
    trap_options:
      source_address:
        address: "{{ ansible_host }}"
