---
all:
  children:
    pod1:
      children:
        spine:
          hosts:
            pod1-spine1:
              ansible_host: "192.168.43.201"
            pod1-spine2:
              ansible_host: "192.168.43.202"
        leaf:
          hosts:
            pod1-leaf1:
              ansible_host: "192.168.43.203"
            pod1-leaf2:
              ansible_host: "192.168.43.204"
            pod1-leaf3:
              ansible_host: "192.168.43.205"
            pod1-leaf4:
              ansible_host: "192.168.43.206"
            pod1-leaf5:
              ansible_host: "192.168.43.207"
            pod1-leaf6:
              ansible_host: "192.168.43.208"
            pod1-leaf7:
              ansible_host: "192.168.43.209"
            pod1-leaf8:
              ansible_host: "192.168.43.210"