---
all:
  children:
    campus:
      children:
        core:
          hosts:
            core-sw1:
              ansible_host: "10.9.9.207"
            core-sw2:
              ansible_host: "10.9.9.208"
        distribution:
          hosts:
            dist-sw1:
              ansible_host: "10.9.9.215"
            dist-sw2:
              ansible_host: "10.9.9.216"
            dist-sw3:
              ansible_host: "10.9.9.217"
            dist-sw4:
              ansible_host: "10.9.9.218"
        access:
          hosts:
            access-sw1:
              ansible_host: "10.9.9.211"
            access-sw2:
              ansible_host: "10.9.9.212"
            access-sw3:
              ansible_host: "10.9.9.213"
            access-sw4:
              ansible_host: "10.9.9.214"
