configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/0
        description: "[xe-0/0/0] to core-sw1 (member of ae11)"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/1
        description: "[xe-0/0/1] to core-sw1 (member of ae11)"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/2
        description: "[xe-0/0/2] to core-sw2 (member of ae12)"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/3
        description: "[xe-0/0/3] to core-sw2 (member of ae12)"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/4
        description: "[xe-0/0/4] to access-sw1 (member of ae1)"
        ether_options:
          ieee_802.3ad:
            bundle: ae1

      - name: xe-0/0/5
        description: "[xe-0/0/5] to access-sw1 (member of ae1)"
        ether_options:
          ieee_802.3ad:
            bundle: ae1

      - name: xe-0/0/6
        description: "[xe-0/0/6] to access-sw2 (member of ae2)"
        ether_options:
          ieee_802.3ad:
            bundle: ae2

      - name: xe-0/0/7
        description: "[xe-0/0/7] to access-sw2 (member of ae2)"
        ether_options:
          ieee_802.3ad:
            bundle: ae2

      # ### AE INTERFACES
      - name: ae11
        description: "[xe-0/0/0-1] to core-sw1"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.1.1/31"

      - name: ae12
        description: "[xe-0/0/2-3] to core-sw1"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "172.16.2.1/31"

      - name: ae1
        description: "[xe-0/0/4-5] to access-sw1"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:01
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:01
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1 
                    - vlan_2 
                    - vlan_3

      - name: ae2
        description: "[xe-0/0/6-7] to access-sw2"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
            system_id: 00:40:00:00:00:02
        esi:
          all_active: null
          identifier: 00:11:11:11:11:11:11:11:11:02
        unit:
          - name: "0"
            family:
              ethernet_switching:
                interface_mode: trunk
                vlan:
                  members:
                    - vlan_1 
                    - vlan_2 
                    - vlan_3

      # ### MGMT INTERFACE
      - name: em0
        unit:
          name: "0"
          description: "out of band interface"
          family:
            inet:
              address:
                name: "{{ ansible_host }}/24"
                # arp:
                #   - name: "192.168.43.1"
                #     mac: "f4:a7:39:1b:d4:9b"

      # ### vQFX PFE INTERFACE
      - name: em1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "169.254.0.2/24"

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"