---
### -------------------------------------------------
### APPLY CONFIGURATION
### -------------------------------------------------
- name: "### APPLY CANDIDATE CONFIGURATION ON REMOTE DEVICE ###"
  juniper_junos_config:
    load: override
    user: "{{ provider_info.user }}"
    passwd: "{{ provider_info.passwd }}"
    # ssh_private_key_file: "{{ provider_info.ssh_private_key_file }}"
    src: "{{ build_completed_file }}"
    timeout: 240
  register: result
  when: is_diff is defined

- name: "### PRINT THE RESULT TO CONSOLE ###"
  debug:
    var: result.diff_lines
  when: result.diff_lines is defined