  
configuration:
  protocols:

    bgp:
      group:

        # ### OVERLAY
        - name: "EVPN_FABRIC"
          type: internal
          cluster: 0.0.0.1
          local_address: "{{ device.lo0.ipv4 }}"
          family:
            evpn:
              signaling: null
          neighbor:
            - description: "dist-sw1"
              name: 192.168.0.11
            - description: "dist-sw2"
              name: 192.168.0.12
            - description: "dist-sw3"
              name: 192.168.0.13
            - description: "dist-sw4"
              name: 192.168.0.14
          # export: "reject-type5"
          multipath: null
          vpn_apply_export: null

    # evpn:
    #   encapsulation: "vxlan"
    #   default_gateway: "no-gateway-community"
    #   extended_vni_list:
    #     - "5001"
    #     - "5002"
    #     - "5003"

    # igmp_snooping:
    #   vlan:
    #     - name: "vlan_1"
    #       interface: "ae11.0"
    #       multicast_router_interface: null

    ospf:
      area:
        - name: "0.0.0.0"
          interface:
            - name: "ae11.0"
            - name: "ae12.0"
            - name: "ae13.0"
            - name: "ae14.0"
            - name: "ae16.0"
            - name: "lo0.0"
              passive: null