configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/0
        description: "[xe-0/0/0] Connected to dist-sw2 xe-0/0/0"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/1
        description: "[xe-0/0/1] Connected to dist-sw2 xe-0/0/1"
        ether_options:
          ieee_802.3ad:
            bundle: ae12

      - name: xe-0/0/2
        description: "[xe-0/0/2] Connected to dist-sw1 xe-0/0/2"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/3
        description: "[xe-0/0/3] Connected to dist-sw1 xe-0/0/3"
        ether_options:
          ieee_802.3ad:
            bundle: ae11

      - name: xe-0/0/8
        description: "[xe-0/0/8] Connected to dist-sw4 xe-0/0/8"
        ether_options:
          ieee_802.3ad:
            bundle: ae14

      - name: xe-0/0/9
        description: "[xe-0/0/9] Connected to dist-sw4 xe-0/0/9"
        ether_options:
          ieee_802.3ad:
            bundle: ae14
    
      - name: xe-0/0/10
        description: "[xe-0/0/10] Connected to dist-sw3 xe-0/0/10"
        ether_options:
          ieee_802.3ad:
            bundle: ae13

      - name: xe-0/0/11
        description: "[xe-0/0/11] Connected to dist-sw3 xe-0/0/11"
        ether_options:
          ieee_802.3ad:
            bundle: ae13

      # ### AE INTERFACES
      - name: ae11
        description: "Connected to dist-sw1 (members: xe-0/0/2-3)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.2.11.0/31"

      - name: ae12
        description: "Connected to dist-sw2 (members: xe-0/0/2-3)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.2.12.0/31"

      - name: ae13
        description: "Connected to dist-sw3 (members: xe-0/0/10-11)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.2.13.0/31"

      - name: ae14
        description: "Connected to dist-sw4 (members: xe-0/0/8-9)"
        apply_groups:
          - AE_MTU_JUMBO
          - AE_LACP_BOND
        aggregated_ether_options:
          lacp:
            active: null
          minimum_links: 1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.2.14.0/31"

      # - name: ae16
      #   description: "Connected to srx (members: xe-0/1/6-7)"
      #   apply_groups:
      #     - AE_MTU_JUMBO
      #     - AE_LACP_BOND
      #   aggregated_ether_options:
      #     lacp:
      #       active: null
      #     minimum_links: 1
      #   unit:
      #     - name: "0"
      #       family:
      #         ethernet_switching:
      #           interface_mode: trunk
      #           vlan:
      #             members:
      #               - vlan4_61
      #               - vlan4_65

      # ### IRB interfaces
      - name: irb
        apply_groups:
          - IRB_OPTIONS
        unit:

          # ### VLAN 1
          - name: "1"
            family:
              inet:
                address:
                  name: "172.20.1.252/24"
                  virtual_gateway_address: "172.20.1.250"
              inet6:
                address:
                  - name: "2001:db8::172:20:1:252/112"
                    virtual_gateway_address: "2001:db8::172:20:1:250"
                  - name: "fe80::172:20:1:252/112"

          # ### VLAN 2
          - name: "2"
            family:
              inet:
                address:
                  name: "172.20.2.252/24"
                  virtual_gateway_address: "172.20.2.250"
              inet6:
                address:
                  - name: "2001:db8::172:20:2:252/112"
                    virtual_gateway_address: "2001:db8::172:20:2:250"
                  - name: "fe80::172:20:2:252/112"

          # ### VLAN 3
          - name: "3"
            family:
              inet:
                address:
                  name: "172.20.3.252/24"
                  virtual_gateway_address: "172.20.3.250"
              inet6:
                address:
                  - name: "2001:db8::172:20:3:252/112"
                    virtual_gateway_address: "2001:db8::172:20:3:250"
                  - name: "fe80::172:20:3:252/112"

          # ### VLAN 61
          - name: "61"
            family:
              inet:
                address:
                  name: "172.30.1.252/24"
                  virtual_gateway_address: "172.30.1.250"
              inet6:
                address:
                  - name: "abcd::60:0:1:252/112"
                    virtual_gateway_address: "abcd::60:0:1:250"
                  - name: "fe80::60:0:1:252/112"

          # ### VLAN 62
          - name: "62"
            family:
              inet:
                address:
                  name: "172.30.2.252/24"
                  virtual_gateway_address: "172.30.2.250"
              inet6:
                address:
                  - name: "abcd::60:0:2:252/112"
                    virtual_gateway_address: "abcd::60:0:2:250"
                  - name: "fe80::60:0:2:252/112"

          # ### VLAN 63
          - name: "63"
            family:
              inet:
                address:
                  name: "172.30.3.252/24"
                  virtual_gateway_address: "172.30.3.250"
              inet6:
                address:
                  - name: "abcd::60:0:3:252/112"
                    virtual_gateway_address: "abcd::60:0:3:250"
                  - name: "fe80::60:0:3:252/112"

          # ### VLAN 64
          - name: "64"
            family:
              inet:
                address:
                  name: "172.30.4.252/24"
                  virtual_gateway_address: "172.30.4.250"
              inet6:
                address:
                  - name: "abcd::60:0:4:252/112"
                    virtual_gateway_address: "abcd::60:0:4:250"
                  - name: "fe80::60:0:4:252/112"

          # ### VLAN 65
          - name: "65"
            family:
              inet:
                address:
                  name: "172.30.5.252/24"
                  virtual_gateway_address: "172.30.5.250"
              inet6:
                address:
                  - name: "abcd::60:0:5:252/112"
                    virtual_gateway_address: "abcd::60:0:5:250"
                  - name: "fe80::60:0:5:252/112"

          # ### VLAN 66
          - name: "66"
            family:
              inet:
                address:
                  name: "172.30.6.252/24"
                  virtual_gateway_address: "172.30.6.250"
              inet6:
                address:
                  - name: "abcd::60:0:6:252/112"
                    virtual_gateway_address: "abcd::60:0:6:250"
                  - name: "fe80::60:0:6:252/112"

          # ### VLAN 67
          - name: "67"
            family:
              inet:
                address:
                  name: "172.30.7.252/24"
                  virtual_gateway_address: "172.30.7.250"
              inet6:
                address:
                  - name: "abcd::60:0:7:252/112"
                    virtual_gateway_address: "abcd::60:0:7:250"
                  - name: "fe80::60:0:7:252/112"

          # ### VLAN 68
          - name: "68"
            family:
              inet:
                address:
                  name: "172.30.8.252/24"
                  virtual_gateway_address: "172.30.8.250"
              inet6:
                address:
                  - name: "abcd::60:0:8:252/112"
                    virtual_gateway_address: "abcd::60:0:8:250"
                  - name: "fe80::60:0:8:252/112"

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"

          - name: "1"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo1.ipv4 }}/32"

          - name: "3001"
            description: "evpn_type5_vrf__3001"
            family:
              inet:
                address:
                  name: "{{ device.lo3001.ipv4 }}/32"
