configuration:
  vlans:
    vlan:
      - name: vlan_101
        description: "MANAGEMENT VLAN"
        vlan_id: "101"
        vxlan:
          vni: 5101
          ingress_node_replication: null

      - name: vlan_102
        description: "PC VLAN"
        vlan_id: "102"
        vxlan:
          vni: 5102
          ingress_node_replication: null

      - name: vlan_103
        description: "WIRELESS VLAN"
        vlan_id: "103"
        vxlan:
          vni: 5103
          ingress_node_replication: null
