configuration:
  interfaces:
    interface:
      # ### PHYSICAL INTERFACES
      - name: xe-0/0/0
        description: "[xe-0/0/0] to pod1-leaf1"
        mtu: "9192"
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.255.255.0/31"

      - name: xe-0/0/1
        description: "[xe-0/0/1] to pod1-leaf2"
        mtu: "9192"
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.255.255.4/31"

      - name: xe-0/0/2
        description: "[xe-0/0/0] to pod1-leaf3"
        mtu: "9192"
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.255.255.8/31"

      - name: xe-0/0/3
        description: "[xe-0/0/1] to pod1-leaf4"
        mtu: "9192"
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.255.255.12/31"

      - name: xe-0/0/4
        description: "[xe-0/0/4] to pod1-leaf5"
        mtu: "9192"
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.255.255.16/31"

      - name: xe-0/0/5
        description: "[xe-0/0/5] to pod1-leaf6"
        mtu: "9192"
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.255.255.20/31"

      - name: xe-0/0/6
        description: "[xe-0/0/6] to pod1-leaf7"
        mtu: "9192"
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.255.255.24/31"

      - name: xe-0/0/7
        description: "[xe-0/0/7] to pod1-leaf8"
        mtu: "9192"
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "10.255.255.28/31"

      # ### IRB interfaces
      - name: irb
        unit:

          # ### VLAN 101
          - name: "101"
            family:
              inet:
                address:
                  name: "10.10.101.2/24"
                  virtual_gateway_address: "10.10.101.1"
                  preferred: null
                  primary: null
              inet6:
                address:
                  - name: "2001:db8::10:10:101:2/112"
                    virtual_gateway_address: "2001:db8::10:10:101:1"
                  - name: "fe80::10:10:101:1/112"
            proxy_macip_advertisement: null
            virtual_gateway_accept_data: null
            virtual_gateway_v4_mac: 00:5e:5e:5e:00:01

          # ### VLAN 102
          - name: "102"
            family:
              inet:
                address:
                  name: "10.10.102.2/24"
                  virtual_gateway_address: "10.10.102.1"
                  preferred: null
                  primary: null
              inet6:
                address:
                  - name: "2001:db8::10:10:102:2/112"
                    virtual_gateway_address: "2001:db8::10:10:102:1"
                  - name: "fe80::10:10:102:1/112"
            proxy_macip_advertisement: null
            virtual_gateway_accept_data: null
            virtual_gateway_v4_mac: 00:5e:5e:5e:00:01

          # ### VLAN 103
          - name: "103"
            family:
              inet:
                address:
                  name: "10.10.103.2/24"
                  virtual_gateway_address: "10.10.103.1"
                  preferred: null
                  primary: null
              inet6:
                address:
                  - name: "2001:db8::10:10:103:2/112"
                    virtual_gateway_address: "2001:db8::10:10:103:1"
                  - name: "fe80::10:10:103:1/112"
            proxy_macip_advertisement: null
            virtual_gateway_accept_data: null
            virtual_gateway_v4_mac: 00:5e:5e:5e:00:01

      # ### MGMT INTERFACE
      - name: em0
        unit:
          name: "0"
          description: "out of band interface"
          family:
            inet:
              address:
                name: "{{ ansible_host }}/24"
                # arp:
                #   - name: "192.168.43.1"
                #     mac: "f4:a7:39:1b:d4:9b"

      # ### vQFX PFE INTERFACE
      - name: em1
        unit:
          name: "0"
          family:
            inet:
              address:
                name: "169.254.0.2/24"

      # ### LOOPBACK INTERFACES
      - name: lo0
        unit:
          - name: "0"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo0.ipv4 }}/32"

          - name: "1"
            description: loopback
            family:
              inet:
                address:
                  name: "{{ device.lo1.ipv4 }}/32"
